import Head from 'next/head'

import Hero from '../components/Hero'
import Profile from '../components/Profile'
import BestSeller from '../components/BestSeller'


export default function Home() {
  return (
    <div>
      <Head>
        <title>ISTEK-AK Press</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
 
     
      <Hero />
      <Profile />
      <BestSeller />
      

    
    </div>
  )
}
